/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as publicRouteRouteImport } from "./routes/(public)/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as adminRouteRouteImport } from "./routes/(admin)/route";
import { Route as publicIndexRouteImport } from "./routes/(public)/index";
import { Route as authAuthRouteImport } from "./routes/(auth)/auth";
import { Route as adminAdminRouteImport } from "./routes/(admin)/admin";
import { Route as publicDesignersIndexRouteImport } from "./routes/(public)/designers/index";
import { Route as publicCollectionsIndexRouteImport } from "./routes/(public)/collections/index";
import { Route as mainChar126GeneralRouteRouteImport } from "./routes/(main)/~/general/route";
import { Route as mainChar126ArtistRouteRouteImport } from "./routes/(main)/~/artist/route";
import { Route as mainChar126GeneralMessagesRouteRouteImport } from "./routes/(main)/~/general/messages/route";
import { Route as mainChar126GeneralWishlistsIndexRouteImport } from "./routes/(main)/~/general/wishlists/index";
import { Route as mainChar126GeneralSettingsIndexRouteImport } from "./routes/(main)/~/general/settings/index";
import { Route as mainChar126GeneralPurchasedModelsIndexRouteImport } from "./routes/(main)/~/general/purchased-models/index";
import { Route as mainChar126GeneralPaymentMethodsIndexRouteImport } from "./routes/(main)/~/general/payment-methods/index";
import { Route as mainChar126GeneralNotificationsIndexRouteImport } from "./routes/(main)/~/general/notifications/index";
import { Route as mainChar126GeneralMessagesIndexRouteImport } from "./routes/(main)/~/general/messages/index";
import { Route as mainChar126GeneralInvoicesIndexRouteImport } from "./routes/(main)/~/general/invoices/index";
import { Route as mainChar126GeneralFeedIndexRouteImport } from "./routes/(main)/~/general/feed/index";
import { Route as mainChar126GeneralFavoritesIndexRouteImport } from "./routes/(main)/~/general/favorites/index";
import { Route as mainChar126GeneralFaqIndexRouteImport } from "./routes/(main)/~/general/faq/index";
import { Route as mainChar126GeneralExploreIndexRouteImport } from "./routes/(main)/~/general/explore/index";
import { Route as mainChar126GeneralContactSupportIndexRouteImport } from "./routes/(main)/~/general/contact-support/index";
import { Route as mainChar126GeneralCartIndexRouteImport } from "./routes/(main)/~/general/cart/index";
import { Route as mainChar126ArtistPublishingIndexRouteImport } from "./routes/(main)/~/artist/publishing/index";
import { Route as mainChar126ArtistMyModelsIndexRouteImport } from "./routes/(main)/~/artist/my-models/index";
import { Route as mainChar126ArtistMessagesIndexRouteImport } from "./routes/(main)/~/artist/messages/index";
import { Route as mainChar126ArtistEarningsIndexRouteImport } from "./routes/(main)/~/artist/earnings/index";
import { Route as mainChar126ArtistDraftsIndexRouteImport } from "./routes/(main)/~/artist/drafts/index";
import { Route as mainChar126ArtistDashboardIndexRouteImport } from "./routes/(main)/~/artist/dashboard/index";
import { Route as mainChar126ArtistCommunityIndexRouteImport } from "./routes/(main)/~/artist/community/index";
import { Route as mainChar126GeneralUUserIdRouteImport } from "./routes/(main)/~/general/u/$userId";
import { Route as mainChar126GeneralPaymentsStatusRouteImport } from "./routes/(main)/~/general/payments/$status";
import { Route as mainChar126GeneralAssetsAssetIdRouteImport } from "./routes/(main)/~/general/assets/$assetId";
import { Route as mainChar126ArtistMessagesUserIdRouteImport } from "./routes/(main)/~/artist/messages/$userId";
import { Route as mainChar126ArtistAssetsAssetIdRouteImport } from "./routes/(main)/~/artist/assets/$assetId";
import { Route as mainChar126GeneralPaymentsReceiptIndexRouteImport } from "./routes/(main)/~/general/payments/receipt/index";
import { Route as mainChar126GeneralPaymentsReceiptReceiptIdRouteImport } from "./routes/(main)/~/general/payments/receipt/$receiptId";
import { Route as mainChar126ArtistPublishingEditAssetIdRouteImport } from "./routes/(main)/~/artist/publishing/edit/$assetId";
import { ServerRoute as ApiMidtransNotificationServerRouteImport } from "./routes/api/midtrans/notification";
import { ServerRoute as ApiImagekitUploadServerRouteImport } from "./routes/api/imagekit/upload";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const publicRouteRoute = publicRouteRouteImport.update({
  id: "/(public)",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const adminRouteRoute = adminRouteRouteImport.update({
  id: "/(admin)",
  getParentRoute: () => rootRouteImport,
} as any);
const publicIndexRoute = publicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicRouteRoute,
} as any);
const authAuthRoute = authAuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => authRouteRoute,
} as any);
const adminAdminRoute = adminAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => adminRouteRoute,
} as any);
const publicDesignersIndexRoute = publicDesignersIndexRouteImport.update({
  id: "/designers/",
  path: "/designers/",
  getParentRoute: () => publicRouteRoute,
} as any);
const publicCollectionsIndexRoute = publicCollectionsIndexRouteImport.update({
  id: "/collections/",
  path: "/collections/",
  getParentRoute: () => publicRouteRoute,
} as any);
const mainChar126GeneralRouteRoute = mainChar126GeneralRouteRouteImport.update({
  id: "/(main)/~/general",
  path: "/~/general",
  getParentRoute: () => rootRouteImport,
} as any);
const mainChar126ArtistRouteRoute = mainChar126ArtistRouteRouteImport.update({
  id: "/(main)/~/artist",
  path: "/~/artist",
  getParentRoute: () => rootRouteImport,
} as any);
const mainChar126GeneralMessagesRouteRoute =
  mainChar126GeneralMessagesRouteRouteImport.update({
    id: "/messages",
    path: "/messages",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralWishlistsIndexRoute =
  mainChar126GeneralWishlistsIndexRouteImport.update({
    id: "/wishlists/",
    path: "/wishlists/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralSettingsIndexRoute =
  mainChar126GeneralSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPurchasedModelsIndexRoute =
  mainChar126GeneralPurchasedModelsIndexRouteImport.update({
    id: "/purchased-models/",
    path: "/purchased-models/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPaymentMethodsIndexRoute =
  mainChar126GeneralPaymentMethodsIndexRouteImport.update({
    id: "/payment-methods/",
    path: "/payment-methods/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralNotificationsIndexRoute =
  mainChar126GeneralNotificationsIndexRouteImport.update({
    id: "/notifications/",
    path: "/notifications/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralMessagesIndexRoute =
  mainChar126GeneralMessagesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => mainChar126GeneralMessagesRouteRoute,
  } as any);
const mainChar126GeneralInvoicesIndexRoute =
  mainChar126GeneralInvoicesIndexRouteImport.update({
    id: "/invoices/",
    path: "/invoices/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralFeedIndexRoute =
  mainChar126GeneralFeedIndexRouteImport.update({
    id: "/feed/",
    path: "/feed/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralFavoritesIndexRoute =
  mainChar126GeneralFavoritesIndexRouteImport.update({
    id: "/favorites/",
    path: "/favorites/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralFaqIndexRoute =
  mainChar126GeneralFaqIndexRouteImport.update({
    id: "/faq/",
    path: "/faq/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralExploreIndexRoute =
  mainChar126GeneralExploreIndexRouteImport.update({
    id: "/explore/",
    path: "/explore/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralContactSupportIndexRoute =
  mainChar126GeneralContactSupportIndexRouteImport.update({
    id: "/contact-support/",
    path: "/contact-support/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralCartIndexRoute =
  mainChar126GeneralCartIndexRouteImport.update({
    id: "/cart/",
    path: "/cart/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126ArtistPublishingIndexRoute =
  mainChar126ArtistPublishingIndexRouteImport.update({
    id: "/publishing/",
    path: "/publishing/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistMyModelsIndexRoute =
  mainChar126ArtistMyModelsIndexRouteImport.update({
    id: "/my-models/",
    path: "/my-models/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistMessagesIndexRoute =
  mainChar126ArtistMessagesIndexRouteImport.update({
    id: "/messages/",
    path: "/messages/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistEarningsIndexRoute =
  mainChar126ArtistEarningsIndexRouteImport.update({
    id: "/earnings/",
    path: "/earnings/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistDraftsIndexRoute =
  mainChar126ArtistDraftsIndexRouteImport.update({
    id: "/drafts/",
    path: "/drafts/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistDashboardIndexRoute =
  mainChar126ArtistDashboardIndexRouteImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistCommunityIndexRoute =
  mainChar126ArtistCommunityIndexRouteImport.update({
    id: "/community/",
    path: "/community/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126GeneralUUserIdRoute =
  mainChar126GeneralUUserIdRouteImport.update({
    id: "/u/$userId",
    path: "/u/$userId",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPaymentsStatusRoute =
  mainChar126GeneralPaymentsStatusRouteImport.update({
    id: "/payments/$status",
    path: "/payments/$status",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralAssetsAssetIdRoute =
  mainChar126GeneralAssetsAssetIdRouteImport.update({
    id: "/assets/$assetId",
    path: "/assets/$assetId",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126ArtistMessagesUserIdRoute =
  mainChar126ArtistMessagesUserIdRouteImport.update({
    id: "/messages/$userId",
    path: "/messages/$userId",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistAssetsAssetIdRoute =
  mainChar126ArtistAssetsAssetIdRouteImport.update({
    id: "/assets/$assetId",
    path: "/assets/$assetId",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126GeneralPaymentsReceiptIndexRoute =
  mainChar126GeneralPaymentsReceiptIndexRouteImport.update({
    id: "/payments/receipt/",
    path: "/payments/receipt/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPaymentsReceiptReceiptIdRoute =
  mainChar126GeneralPaymentsReceiptReceiptIdRouteImport.update({
    id: "/payments/receipt/$receiptId",
    path: "/payments/receipt/$receiptId",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126ArtistPublishingEditAssetIdRoute =
  mainChar126ArtistPublishingEditAssetIdRouteImport.update({
    id: "/publishing/edit/$assetId",
    path: "/publishing/edit/$assetId",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const ApiMidtransNotificationServerRoute =
  ApiMidtransNotificationServerRouteImport.update({
    id: "/api/midtrans/notification",
    path: "/api/midtrans/notification",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiImagekitUploadServerRoute = ApiImagekitUploadServerRouteImport.update({
  id: "/api/imagekit/upload",
  path: "/api/imagekit/upload",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof publicIndexRoute;
  "/admin": typeof adminAdminRoute;
  "/auth": typeof authAuthRoute;
  "/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/collections": typeof publicCollectionsIndexRoute;
  "/designers": typeof publicDesignersIndexRoute;
  "/~/general/messages": typeof mainChar126GeneralMessagesRouteRouteWithChildren;
  "/~/artist/assets/$assetId": typeof mainChar126ArtistAssetsAssetIdRoute;
  "/~/artist/messages/$userId": typeof mainChar126ArtistMessagesUserIdRoute;
  "/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/~/artist/community": typeof mainChar126ArtistCommunityIndexRoute;
  "/~/artist/dashboard": typeof mainChar126ArtistDashboardIndexRoute;
  "/~/artist/drafts": typeof mainChar126ArtistDraftsIndexRoute;
  "/~/artist/earnings": typeof mainChar126ArtistEarningsIndexRoute;
  "/~/artist/messages": typeof mainChar126ArtistMessagesIndexRoute;
  "/~/artist/my-models": typeof mainChar126ArtistMyModelsIndexRoute;
  "/~/artist/publishing": typeof mainChar126ArtistPublishingIndexRoute;
  "/~/general/cart": typeof mainChar126GeneralCartIndexRoute;
  "/~/general/contact-support": typeof mainChar126GeneralContactSupportIndexRoute;
  "/~/general/explore": typeof mainChar126GeneralExploreIndexRoute;
  "/~/general/faq": typeof mainChar126GeneralFaqIndexRoute;
  "/~/general/favorites": typeof mainChar126GeneralFavoritesIndexRoute;
  "/~/general/feed": typeof mainChar126GeneralFeedIndexRoute;
  "/~/general/invoices": typeof mainChar126GeneralInvoicesIndexRoute;
  "/~/general/messages/": typeof mainChar126GeneralMessagesIndexRoute;
  "/~/general/notifications": typeof mainChar126GeneralNotificationsIndexRoute;
  "/~/general/payment-methods": typeof mainChar126GeneralPaymentMethodsIndexRoute;
  "/~/general/purchased-models": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/~/general/settings": typeof mainChar126GeneralSettingsIndexRoute;
  "/~/general/wishlists": typeof mainChar126GeneralWishlistsIndexRoute;
  "/~/artist/publishing/edit/$assetId": typeof mainChar126ArtistPublishingEditAssetIdRoute;
  "/~/general/payments/receipt/$receiptId": typeof mainChar126GeneralPaymentsReceiptReceiptIdRoute;
  "/~/general/payments/receipt": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof publicIndexRoute;
  "/admin": typeof adminAdminRoute;
  "/auth": typeof authAuthRoute;
  "/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/collections": typeof publicCollectionsIndexRoute;
  "/designers": typeof publicDesignersIndexRoute;
  "/~/artist/assets/$assetId": typeof mainChar126ArtistAssetsAssetIdRoute;
  "/~/artist/messages/$userId": typeof mainChar126ArtistMessagesUserIdRoute;
  "/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/~/artist/community": typeof mainChar126ArtistCommunityIndexRoute;
  "/~/artist/dashboard": typeof mainChar126ArtistDashboardIndexRoute;
  "/~/artist/drafts": typeof mainChar126ArtistDraftsIndexRoute;
  "/~/artist/earnings": typeof mainChar126ArtistEarningsIndexRoute;
  "/~/artist/messages": typeof mainChar126ArtistMessagesIndexRoute;
  "/~/artist/my-models": typeof mainChar126ArtistMyModelsIndexRoute;
  "/~/artist/publishing": typeof mainChar126ArtistPublishingIndexRoute;
  "/~/general/cart": typeof mainChar126GeneralCartIndexRoute;
  "/~/general/contact-support": typeof mainChar126GeneralContactSupportIndexRoute;
  "/~/general/explore": typeof mainChar126GeneralExploreIndexRoute;
  "/~/general/faq": typeof mainChar126GeneralFaqIndexRoute;
  "/~/general/favorites": typeof mainChar126GeneralFavoritesIndexRoute;
  "/~/general/feed": typeof mainChar126GeneralFeedIndexRoute;
  "/~/general/invoices": typeof mainChar126GeneralInvoicesIndexRoute;
  "/~/general/messages": typeof mainChar126GeneralMessagesIndexRoute;
  "/~/general/notifications": typeof mainChar126GeneralNotificationsIndexRoute;
  "/~/general/payment-methods": typeof mainChar126GeneralPaymentMethodsIndexRoute;
  "/~/general/purchased-models": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/~/general/settings": typeof mainChar126GeneralSettingsIndexRoute;
  "/~/general/wishlists": typeof mainChar126GeneralWishlistsIndexRoute;
  "/~/artist/publishing/edit/$assetId": typeof mainChar126ArtistPublishingEditAssetIdRoute;
  "/~/general/payments/receipt/$receiptId": typeof mainChar126GeneralPaymentsReceiptReceiptIdRoute;
  "/~/general/payments/receipt": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(admin)": typeof adminRouteRouteWithChildren;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/(public)": typeof publicRouteRouteWithChildren;
  "/(admin)/admin": typeof adminAdminRoute;
  "/(auth)/auth": typeof authAuthRoute;
  "/(public)/": typeof publicIndexRoute;
  "/(main)/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/(main)/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/(public)/collections/": typeof publicCollectionsIndexRoute;
  "/(public)/designers/": typeof publicDesignersIndexRoute;
  "/(main)/~/general/messages": typeof mainChar126GeneralMessagesRouteRouteWithChildren;
  "/(main)/~/artist/assets/$assetId": typeof mainChar126ArtistAssetsAssetIdRoute;
  "/(main)/~/artist/messages/$userId": typeof mainChar126ArtistMessagesUserIdRoute;
  "/(main)/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/(main)/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/(main)/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/(main)/~/artist/community/": typeof mainChar126ArtistCommunityIndexRoute;
  "/(main)/~/artist/dashboard/": typeof mainChar126ArtistDashboardIndexRoute;
  "/(main)/~/artist/drafts/": typeof mainChar126ArtistDraftsIndexRoute;
  "/(main)/~/artist/earnings/": typeof mainChar126ArtistEarningsIndexRoute;
  "/(main)/~/artist/messages/": typeof mainChar126ArtistMessagesIndexRoute;
  "/(main)/~/artist/my-models/": typeof mainChar126ArtistMyModelsIndexRoute;
  "/(main)/~/artist/publishing/": typeof mainChar126ArtistPublishingIndexRoute;
  "/(main)/~/general/cart/": typeof mainChar126GeneralCartIndexRoute;
  "/(main)/~/general/contact-support/": typeof mainChar126GeneralContactSupportIndexRoute;
  "/(main)/~/general/explore/": typeof mainChar126GeneralExploreIndexRoute;
  "/(main)/~/general/faq/": typeof mainChar126GeneralFaqIndexRoute;
  "/(main)/~/general/favorites/": typeof mainChar126GeneralFavoritesIndexRoute;
  "/(main)/~/general/feed/": typeof mainChar126GeneralFeedIndexRoute;
  "/(main)/~/general/invoices/": typeof mainChar126GeneralInvoicesIndexRoute;
  "/(main)/~/general/messages/": typeof mainChar126GeneralMessagesIndexRoute;
  "/(main)/~/general/notifications/": typeof mainChar126GeneralNotificationsIndexRoute;
  "/(main)/~/general/payment-methods/": typeof mainChar126GeneralPaymentMethodsIndexRoute;
  "/(main)/~/general/purchased-models/": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/(main)/~/general/settings/": typeof mainChar126GeneralSettingsIndexRoute;
  "/(main)/~/general/wishlists/": typeof mainChar126GeneralWishlistsIndexRoute;
  "/(main)/~/artist/publishing/edit/$assetId": typeof mainChar126ArtistPublishingEditAssetIdRoute;
  "/(main)/~/general/payments/receipt/$receiptId": typeof mainChar126GeneralPaymentsReceiptReceiptIdRoute;
  "/(main)/~/general/payments/receipt/": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/auth"
    | "/~/artist"
    | "/~/general"
    | "/collections"
    | "/designers"
    | "/~/general/messages"
    | "/~/artist/assets/$assetId"
    | "/~/artist/messages/$userId"
    | "/~/general/assets/$assetId"
    | "/~/general/payments/$status"
    | "/~/general/u/$userId"
    | "/~/artist/community"
    | "/~/artist/dashboard"
    | "/~/artist/drafts"
    | "/~/artist/earnings"
    | "/~/artist/messages"
    | "/~/artist/my-models"
    | "/~/artist/publishing"
    | "/~/general/cart"
    | "/~/general/contact-support"
    | "/~/general/explore"
    | "/~/general/faq"
    | "/~/general/favorites"
    | "/~/general/feed"
    | "/~/general/invoices"
    | "/~/general/messages/"
    | "/~/general/notifications"
    | "/~/general/payment-methods"
    | "/~/general/purchased-models"
    | "/~/general/settings"
    | "/~/general/wishlists"
    | "/~/artist/publishing/edit/$assetId"
    | "/~/general/payments/receipt/$receiptId"
    | "/~/general/payments/receipt";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/auth"
    | "/~/artist"
    | "/~/general"
    | "/collections"
    | "/designers"
    | "/~/artist/assets/$assetId"
    | "/~/artist/messages/$userId"
    | "/~/general/assets/$assetId"
    | "/~/general/payments/$status"
    | "/~/general/u/$userId"
    | "/~/artist/community"
    | "/~/artist/dashboard"
    | "/~/artist/drafts"
    | "/~/artist/earnings"
    | "/~/artist/messages"
    | "/~/artist/my-models"
    | "/~/artist/publishing"
    | "/~/general/cart"
    | "/~/general/contact-support"
    | "/~/general/explore"
    | "/~/general/faq"
    | "/~/general/favorites"
    | "/~/general/feed"
    | "/~/general/invoices"
    | "/~/general/messages"
    | "/~/general/notifications"
    | "/~/general/payment-methods"
    | "/~/general/purchased-models"
    | "/~/general/settings"
    | "/~/general/wishlists"
    | "/~/artist/publishing/edit/$assetId"
    | "/~/general/payments/receipt/$receiptId"
    | "/~/general/payments/receipt";
  id:
    | "__root__"
    | "/(admin)"
    | "/(auth)"
    | "/(public)"
    | "/(admin)/admin"
    | "/(auth)/auth"
    | "/(public)/"
    | "/(main)/~/artist"
    | "/(main)/~/general"
    | "/(public)/collections/"
    | "/(public)/designers/"
    | "/(main)/~/general/messages"
    | "/(main)/~/artist/assets/$assetId"
    | "/(main)/~/artist/messages/$userId"
    | "/(main)/~/general/assets/$assetId"
    | "/(main)/~/general/payments/$status"
    | "/(main)/~/general/u/$userId"
    | "/(main)/~/artist/community/"
    | "/(main)/~/artist/dashboard/"
    | "/(main)/~/artist/drafts/"
    | "/(main)/~/artist/earnings/"
    | "/(main)/~/artist/messages/"
    | "/(main)/~/artist/my-models/"
    | "/(main)/~/artist/publishing/"
    | "/(main)/~/general/cart/"
    | "/(main)/~/general/contact-support/"
    | "/(main)/~/general/explore/"
    | "/(main)/~/general/faq/"
    | "/(main)/~/general/favorites/"
    | "/(main)/~/general/feed/"
    | "/(main)/~/general/invoices/"
    | "/(main)/~/general/messages/"
    | "/(main)/~/general/notifications/"
    | "/(main)/~/general/payment-methods/"
    | "/(main)/~/general/purchased-models/"
    | "/(main)/~/general/settings/"
    | "/(main)/~/general/wishlists/"
    | "/(main)/~/artist/publishing/edit/$assetId"
    | "/(main)/~/general/payments/receipt/$receiptId"
    | "/(main)/~/general/payments/receipt/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren;
  authRouteRoute: typeof authRouteRouteWithChildren;
  publicRouteRoute: typeof publicRouteRouteWithChildren;
  mainChar126ArtistRouteRoute: typeof mainChar126ArtistRouteRouteWithChildren;
  mainChar126GeneralRouteRoute: typeof mainChar126GeneralRouteRouteWithChildren;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
  "/api/midtrans/notification": typeof ApiMidtransNotificationServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
  "/api/midtrans/notification": typeof ApiMidtransNotificationServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
  "/api/midtrans/notification": typeof ApiMidtransNotificationServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths:
    | "/api/auth/$"
    | "/api/imagekit/upload"
    | "/api/midtrans/notification";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$" | "/api/imagekit/upload" | "/api/midtrans/notification";
  id:
    | "__root__"
    | "/api/auth/$"
    | "/api/imagekit/upload"
    | "/api/midtrans/notification";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiImagekitUploadServerRoute: typeof ApiImagekitUploadServerRoute;
  ApiMidtransNotificationServerRoute: typeof ApiMidtransNotificationServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(public)": {
      id: "/(public)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(admin)": {
      id: "/(admin)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof adminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/": {
      id: "/(public)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof publicRouteRoute;
    };
    "/(auth)/auth": {
      id: "/(auth)/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof authAuthRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(admin)/admin": {
      id: "/(admin)/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof adminAdminRouteImport;
      parentRoute: typeof adminRouteRoute;
    };
    "/(public)/designers/": {
      id: "/(public)/designers/";
      path: "/designers";
      fullPath: "/designers";
      preLoaderRoute: typeof publicDesignersIndexRouteImport;
      parentRoute: typeof publicRouteRoute;
    };
    "/(public)/collections/": {
      id: "/(public)/collections/";
      path: "/collections";
      fullPath: "/collections";
      preLoaderRoute: typeof publicCollectionsIndexRouteImport;
      parentRoute: typeof publicRouteRoute;
    };
    "/(main)/~/general": {
      id: "/(main)/~/general";
      path: "/~/general";
      fullPath: "/~/general";
      preLoaderRoute: typeof mainChar126GeneralRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/~/artist": {
      id: "/(main)/~/artist";
      path: "/~/artist";
      fullPath: "/~/artist";
      preLoaderRoute: typeof mainChar126ArtistRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/~/general/messages": {
      id: "/(main)/~/general/messages";
      path: "/messages";
      fullPath: "/~/general/messages";
      preLoaderRoute: typeof mainChar126GeneralMessagesRouteRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/wishlists/": {
      id: "/(main)/~/general/wishlists/";
      path: "/wishlists";
      fullPath: "/~/general/wishlists";
      preLoaderRoute: typeof mainChar126GeneralWishlistsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/settings/": {
      id: "/(main)/~/general/settings/";
      path: "/settings";
      fullPath: "/~/general/settings";
      preLoaderRoute: typeof mainChar126GeneralSettingsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/purchased-models/": {
      id: "/(main)/~/general/purchased-models/";
      path: "/purchased-models";
      fullPath: "/~/general/purchased-models";
      preLoaderRoute: typeof mainChar126GeneralPurchasedModelsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/payment-methods/": {
      id: "/(main)/~/general/payment-methods/";
      path: "/payment-methods";
      fullPath: "/~/general/payment-methods";
      preLoaderRoute: typeof mainChar126GeneralPaymentMethodsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/notifications/": {
      id: "/(main)/~/general/notifications/";
      path: "/notifications";
      fullPath: "/~/general/notifications";
      preLoaderRoute: typeof mainChar126GeneralNotificationsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/messages/": {
      id: "/(main)/~/general/messages/";
      path: "/";
      fullPath: "/~/general/messages/";
      preLoaderRoute: typeof mainChar126GeneralMessagesIndexRouteImport;
      parentRoute: typeof mainChar126GeneralMessagesRouteRoute;
    };
    "/(main)/~/general/invoices/": {
      id: "/(main)/~/general/invoices/";
      path: "/invoices";
      fullPath: "/~/general/invoices";
      preLoaderRoute: typeof mainChar126GeneralInvoicesIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/feed/": {
      id: "/(main)/~/general/feed/";
      path: "/feed";
      fullPath: "/~/general/feed";
      preLoaderRoute: typeof mainChar126GeneralFeedIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/favorites/": {
      id: "/(main)/~/general/favorites/";
      path: "/favorites";
      fullPath: "/~/general/favorites";
      preLoaderRoute: typeof mainChar126GeneralFavoritesIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/faq/": {
      id: "/(main)/~/general/faq/";
      path: "/faq";
      fullPath: "/~/general/faq";
      preLoaderRoute: typeof mainChar126GeneralFaqIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/explore/": {
      id: "/(main)/~/general/explore/";
      path: "/explore";
      fullPath: "/~/general/explore";
      preLoaderRoute: typeof mainChar126GeneralExploreIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/contact-support/": {
      id: "/(main)/~/general/contact-support/";
      path: "/contact-support";
      fullPath: "/~/general/contact-support";
      preLoaderRoute: typeof mainChar126GeneralContactSupportIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/cart/": {
      id: "/(main)/~/general/cart/";
      path: "/cart";
      fullPath: "/~/general/cart";
      preLoaderRoute: typeof mainChar126GeneralCartIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/artist/publishing/": {
      id: "/(main)/~/artist/publishing/";
      path: "/publishing";
      fullPath: "/~/artist/publishing";
      preLoaderRoute: typeof mainChar126ArtistPublishingIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/my-models/": {
      id: "/(main)/~/artist/my-models/";
      path: "/my-models";
      fullPath: "/~/artist/my-models";
      preLoaderRoute: typeof mainChar126ArtistMyModelsIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/messages/": {
      id: "/(main)/~/artist/messages/";
      path: "/messages";
      fullPath: "/~/artist/messages";
      preLoaderRoute: typeof mainChar126ArtistMessagesIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/earnings/": {
      id: "/(main)/~/artist/earnings/";
      path: "/earnings";
      fullPath: "/~/artist/earnings";
      preLoaderRoute: typeof mainChar126ArtistEarningsIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/drafts/": {
      id: "/(main)/~/artist/drafts/";
      path: "/drafts";
      fullPath: "/~/artist/drafts";
      preLoaderRoute: typeof mainChar126ArtistDraftsIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/dashboard/": {
      id: "/(main)/~/artist/dashboard/";
      path: "/dashboard";
      fullPath: "/~/artist/dashboard";
      preLoaderRoute: typeof mainChar126ArtistDashboardIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/community/": {
      id: "/(main)/~/artist/community/";
      path: "/community";
      fullPath: "/~/artist/community";
      preLoaderRoute: typeof mainChar126ArtistCommunityIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/general/u/$userId": {
      id: "/(main)/~/general/u/$userId";
      path: "/u/$userId";
      fullPath: "/~/general/u/$userId";
      preLoaderRoute: typeof mainChar126GeneralUUserIdRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/payments/$status": {
      id: "/(main)/~/general/payments/$status";
      path: "/payments/$status";
      fullPath: "/~/general/payments/$status";
      preLoaderRoute: typeof mainChar126GeneralPaymentsStatusRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/assets/$assetId": {
      id: "/(main)/~/general/assets/$assetId";
      path: "/assets/$assetId";
      fullPath: "/~/general/assets/$assetId";
      preLoaderRoute: typeof mainChar126GeneralAssetsAssetIdRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/artist/messages/$userId": {
      id: "/(main)/~/artist/messages/$userId";
      path: "/messages/$userId";
      fullPath: "/~/artist/messages/$userId";
      preLoaderRoute: typeof mainChar126ArtistMessagesUserIdRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/assets/$assetId": {
      id: "/(main)/~/artist/assets/$assetId";
      path: "/assets/$assetId";
      fullPath: "/~/artist/assets/$assetId";
      preLoaderRoute: typeof mainChar126ArtistAssetsAssetIdRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/general/payments/receipt/": {
      id: "/(main)/~/general/payments/receipt/";
      path: "/payments/receipt";
      fullPath: "/~/general/payments/receipt";
      preLoaderRoute: typeof mainChar126GeneralPaymentsReceiptIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/payments/receipt/$receiptId": {
      id: "/(main)/~/general/payments/receipt/$receiptId";
      path: "/payments/receipt/$receiptId";
      fullPath: "/~/general/payments/receipt/$receiptId";
      preLoaderRoute: typeof mainChar126GeneralPaymentsReceiptReceiptIdRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/artist/publishing/edit/$assetId": {
      id: "/(main)/~/artist/publishing/edit/$assetId";
      path: "/publishing/edit/$assetId";
      fullPath: "/~/artist/publishing/edit/$assetId";
      preLoaderRoute: typeof mainChar126ArtistPublishingEditAssetIdRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/midtrans/notification": {
      id: "/api/midtrans/notification";
      path: "/api/midtrans/notification";
      fullPath: "/api/midtrans/notification";
      preLoaderRoute: typeof ApiMidtransNotificationServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/imagekit/upload": {
      id: "/api/imagekit/upload";
      path: "/api/imagekit/upload";
      fullPath: "/api/imagekit/upload";
      preLoaderRoute: typeof ApiImagekitUploadServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface adminRouteRouteChildren {
  adminAdminRoute: typeof adminAdminRoute;
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminRoute: adminAdminRoute,
};

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
);

interface authRouteRouteChildren {
  authAuthRoute: typeof authAuthRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthRoute: authAuthRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute;
  publicCollectionsIndexRoute: typeof publicCollectionsIndexRoute;
  publicDesignersIndexRoute: typeof publicDesignersIndexRoute;
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicCollectionsIndexRoute: publicCollectionsIndexRoute,
  publicDesignersIndexRoute: publicDesignersIndexRoute,
};

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
);

interface mainChar126ArtistRouteRouteChildren {
  mainChar126ArtistAssetsAssetIdRoute: typeof mainChar126ArtistAssetsAssetIdRoute;
  mainChar126ArtistMessagesUserIdRoute: typeof mainChar126ArtistMessagesUserIdRoute;
  mainChar126ArtistCommunityIndexRoute: typeof mainChar126ArtistCommunityIndexRoute;
  mainChar126ArtistDashboardIndexRoute: typeof mainChar126ArtistDashboardIndexRoute;
  mainChar126ArtistDraftsIndexRoute: typeof mainChar126ArtistDraftsIndexRoute;
  mainChar126ArtistEarningsIndexRoute: typeof mainChar126ArtistEarningsIndexRoute;
  mainChar126ArtistMessagesIndexRoute: typeof mainChar126ArtistMessagesIndexRoute;
  mainChar126ArtistMyModelsIndexRoute: typeof mainChar126ArtistMyModelsIndexRoute;
  mainChar126ArtistPublishingIndexRoute: typeof mainChar126ArtistPublishingIndexRoute;
  mainChar126ArtistPublishingEditAssetIdRoute: typeof mainChar126ArtistPublishingEditAssetIdRoute;
}

const mainChar126ArtistRouteRouteChildren: mainChar126ArtistRouteRouteChildren =
  {
    mainChar126ArtistAssetsAssetIdRoute: mainChar126ArtistAssetsAssetIdRoute,
    mainChar126ArtistMessagesUserIdRoute: mainChar126ArtistMessagesUserIdRoute,
    mainChar126ArtistCommunityIndexRoute: mainChar126ArtistCommunityIndexRoute,
    mainChar126ArtistDashboardIndexRoute: mainChar126ArtistDashboardIndexRoute,
    mainChar126ArtistDraftsIndexRoute: mainChar126ArtistDraftsIndexRoute,
    mainChar126ArtistEarningsIndexRoute: mainChar126ArtistEarningsIndexRoute,
    mainChar126ArtistMessagesIndexRoute: mainChar126ArtistMessagesIndexRoute,
    mainChar126ArtistMyModelsIndexRoute: mainChar126ArtistMyModelsIndexRoute,
    mainChar126ArtistPublishingIndexRoute:
      mainChar126ArtistPublishingIndexRoute,
    mainChar126ArtistPublishingEditAssetIdRoute:
      mainChar126ArtistPublishingEditAssetIdRoute,
  };

const mainChar126ArtistRouteRouteWithChildren =
  mainChar126ArtistRouteRoute._addFileChildren(
    mainChar126ArtistRouteRouteChildren,
  );

interface mainChar126GeneralMessagesRouteRouteChildren {
  mainChar126GeneralMessagesIndexRoute: typeof mainChar126GeneralMessagesIndexRoute;
}

const mainChar126GeneralMessagesRouteRouteChildren: mainChar126GeneralMessagesRouteRouteChildren =
  {
    mainChar126GeneralMessagesIndexRoute: mainChar126GeneralMessagesIndexRoute,
  };

const mainChar126GeneralMessagesRouteRouteWithChildren =
  mainChar126GeneralMessagesRouteRoute._addFileChildren(
    mainChar126GeneralMessagesRouteRouteChildren,
  );

interface mainChar126GeneralRouteRouteChildren {
  mainChar126GeneralMessagesRouteRoute: typeof mainChar126GeneralMessagesRouteRouteWithChildren;
  mainChar126GeneralAssetsAssetIdRoute: typeof mainChar126GeneralAssetsAssetIdRoute;
  mainChar126GeneralPaymentsStatusRoute: typeof mainChar126GeneralPaymentsStatusRoute;
  mainChar126GeneralUUserIdRoute: typeof mainChar126GeneralUUserIdRoute;
  mainChar126GeneralCartIndexRoute: typeof mainChar126GeneralCartIndexRoute;
  mainChar126GeneralContactSupportIndexRoute: typeof mainChar126GeneralContactSupportIndexRoute;
  mainChar126GeneralExploreIndexRoute: typeof mainChar126GeneralExploreIndexRoute;
  mainChar126GeneralFaqIndexRoute: typeof mainChar126GeneralFaqIndexRoute;
  mainChar126GeneralFavoritesIndexRoute: typeof mainChar126GeneralFavoritesIndexRoute;
  mainChar126GeneralFeedIndexRoute: typeof mainChar126GeneralFeedIndexRoute;
  mainChar126GeneralInvoicesIndexRoute: typeof mainChar126GeneralInvoicesIndexRoute;
  mainChar126GeneralNotificationsIndexRoute: typeof mainChar126GeneralNotificationsIndexRoute;
  mainChar126GeneralPaymentMethodsIndexRoute: typeof mainChar126GeneralPaymentMethodsIndexRoute;
  mainChar126GeneralPurchasedModelsIndexRoute: typeof mainChar126GeneralPurchasedModelsIndexRoute;
  mainChar126GeneralSettingsIndexRoute: typeof mainChar126GeneralSettingsIndexRoute;
  mainChar126GeneralWishlistsIndexRoute: typeof mainChar126GeneralWishlistsIndexRoute;
  mainChar126GeneralPaymentsReceiptReceiptIdRoute: typeof mainChar126GeneralPaymentsReceiptReceiptIdRoute;
  mainChar126GeneralPaymentsReceiptIndexRoute: typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}

const mainChar126GeneralRouteRouteChildren: mainChar126GeneralRouteRouteChildren =
  {
    mainChar126GeneralMessagesRouteRoute:
      mainChar126GeneralMessagesRouteRouteWithChildren,
    mainChar126GeneralAssetsAssetIdRoute: mainChar126GeneralAssetsAssetIdRoute,
    mainChar126GeneralPaymentsStatusRoute:
      mainChar126GeneralPaymentsStatusRoute,
    mainChar126GeneralUUserIdRoute: mainChar126GeneralUUserIdRoute,
    mainChar126GeneralCartIndexRoute: mainChar126GeneralCartIndexRoute,
    mainChar126GeneralContactSupportIndexRoute:
      mainChar126GeneralContactSupportIndexRoute,
    mainChar126GeneralExploreIndexRoute: mainChar126GeneralExploreIndexRoute,
    mainChar126GeneralFaqIndexRoute: mainChar126GeneralFaqIndexRoute,
    mainChar126GeneralFavoritesIndexRoute:
      mainChar126GeneralFavoritesIndexRoute,
    mainChar126GeneralFeedIndexRoute: mainChar126GeneralFeedIndexRoute,
    mainChar126GeneralInvoicesIndexRoute: mainChar126GeneralInvoicesIndexRoute,
    mainChar126GeneralNotificationsIndexRoute:
      mainChar126GeneralNotificationsIndexRoute,
    mainChar126GeneralPaymentMethodsIndexRoute:
      mainChar126GeneralPaymentMethodsIndexRoute,
    mainChar126GeneralPurchasedModelsIndexRoute:
      mainChar126GeneralPurchasedModelsIndexRoute,
    mainChar126GeneralSettingsIndexRoute: mainChar126GeneralSettingsIndexRoute,
    mainChar126GeneralWishlistsIndexRoute:
      mainChar126GeneralWishlistsIndexRoute,
    mainChar126GeneralPaymentsReceiptReceiptIdRoute:
      mainChar126GeneralPaymentsReceiptReceiptIdRoute,
    mainChar126GeneralPaymentsReceiptIndexRoute:
      mainChar126GeneralPaymentsReceiptIndexRoute,
  };

const mainChar126GeneralRouteRouteWithChildren =
  mainChar126GeneralRouteRoute._addFileChildren(
    mainChar126GeneralRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  mainChar126ArtistRouteRoute: mainChar126ArtistRouteRouteWithChildren,
  mainChar126GeneralRouteRoute: mainChar126GeneralRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiImagekitUploadServerRoute: ApiImagekitUploadServerRoute,
  ApiMidtransNotificationServerRoute: ApiMidtransNotificationServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
