/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as publicPlaygroundsRouteImport } from "./routes/(public)/playgrounds";
import { Route as authAuthRouteImport } from "./routes/(auth)/auth";
import { Route as adminAdminRouteImport } from "./routes/(admin)/admin";
import { Route as mainChar126GeneralRouteRouteImport } from "./routes/(main)/~/general/route";
import { Route as mainChar126ArtistRouteRouteImport } from "./routes/(main)/~/artist/route";
import { Route as mainChar126GeneralWishlistsIndexRouteImport } from "./routes/(main)/~/general/wishlists/index";
import { Route as mainChar126GeneralPurchasedModelsIndexRouteImport } from "./routes/(main)/~/general/purchased-models/index";
import { Route as mainChar126GeneralInvoicesIndexRouteImport } from "./routes/(main)/~/general/invoices/index";
import { Route as mainChar126GeneralFeedIndexRouteImport } from "./routes/(main)/~/general/feed/index";
import { Route as mainChar126GeneralFavoritesIndexRouteImport } from "./routes/(main)/~/general/favorites/index";
import { Route as mainChar126GeneralExploreIndexRouteImport } from "./routes/(main)/~/general/explore/index";
import { Route as mainChar126GeneralCartIndexRouteImport } from "./routes/(main)/~/general/cart/index";
import { Route as mainChar126ArtistPublishingIndexRouteImport } from "./routes/(main)/~/artist/publishing/index";
import { Route as mainChar126ArtistMyModelsIndexRouteImport } from "./routes/(main)/~/artist/my-models/index";
import { Route as mainChar126ArtistDashboardIndexRouteImport } from "./routes/(main)/~/artist/dashboard/index";
import { Route as mainChar126GeneralUUserIdRouteImport } from "./routes/(main)/~/general/u/$userId";
import { Route as mainChar126GeneralPaymentsStatusRouteImport } from "./routes/(main)/~/general/payments/$status";
import { Route as mainChar126GeneralAssetsAssetIdRouteImport } from "./routes/(main)/~/general/assets/$assetId";
import { Route as mainChar126GeneralPaymentsReceiptIndexRouteImport } from "./routes/(main)/~/general/payments/receipt/index";
import { ServerRoute as ApiImagekitUploadServerRouteImport } from "./routes/api/imagekit/upload";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const publicPlaygroundsRoute = publicPlaygroundsRouteImport.update({
  id: "/(public)/playgrounds",
  path: "/playgrounds",
  getParentRoute: () => rootRouteImport,
} as any);
const authAuthRoute = authAuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => authRouteRoute,
} as any);
const adminAdminRoute = adminAdminRouteImport.update({
  id: "/(admin)/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const mainChar126GeneralRouteRoute = mainChar126GeneralRouteRouteImport.update({
  id: "/(main)/~/general",
  path: "/~/general",
  getParentRoute: () => rootRouteImport,
} as any);
const mainChar126ArtistRouteRoute = mainChar126ArtistRouteRouteImport.update({
  id: "/(main)/~/artist",
  path: "/~/artist",
  getParentRoute: () => rootRouteImport,
} as any);
const mainChar126GeneralWishlistsIndexRoute =
  mainChar126GeneralWishlistsIndexRouteImport.update({
    id: "/wishlists/",
    path: "/wishlists/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPurchasedModelsIndexRoute =
  mainChar126GeneralPurchasedModelsIndexRouteImport.update({
    id: "/purchased-models/",
    path: "/purchased-models/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralInvoicesIndexRoute =
  mainChar126GeneralInvoicesIndexRouteImport.update({
    id: "/invoices/",
    path: "/invoices/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralFeedIndexRoute =
  mainChar126GeneralFeedIndexRouteImport.update({
    id: "/feed/",
    path: "/feed/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralFavoritesIndexRoute =
  mainChar126GeneralFavoritesIndexRouteImport.update({
    id: "/favorites/",
    path: "/favorites/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralExploreIndexRoute =
  mainChar126GeneralExploreIndexRouteImport.update({
    id: "/explore/",
    path: "/explore/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralCartIndexRoute =
  mainChar126GeneralCartIndexRouteImport.update({
    id: "/cart/",
    path: "/cart/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126ArtistPublishingIndexRoute =
  mainChar126ArtistPublishingIndexRouteImport.update({
    id: "/publishing/",
    path: "/publishing/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistMyModelsIndexRoute =
  mainChar126ArtistMyModelsIndexRouteImport.update({
    id: "/my-models/",
    path: "/my-models/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126ArtistDashboardIndexRoute =
  mainChar126ArtistDashboardIndexRouteImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => mainChar126ArtistRouteRoute,
  } as any);
const mainChar126GeneralUUserIdRoute =
  mainChar126GeneralUUserIdRouteImport.update({
    id: "/u/$userId",
    path: "/u/$userId",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPaymentsStatusRoute =
  mainChar126GeneralPaymentsStatusRouteImport.update({
    id: "/payments/$status",
    path: "/payments/$status",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralAssetsAssetIdRoute =
  mainChar126GeneralAssetsAssetIdRouteImport.update({
    id: "/assets/$assetId",
    path: "/assets/$assetId",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const mainChar126GeneralPaymentsReceiptIndexRoute =
  mainChar126GeneralPaymentsReceiptIndexRouteImport.update({
    id: "/payments/receipt/",
    path: "/payments/receipt/",
    getParentRoute: () => mainChar126GeneralRouteRoute,
  } as any);
const ApiImagekitUploadServerRoute = ApiImagekitUploadServerRouteImport.update({
  id: "/api/imagekit/upload",
  path: "/api/imagekit/upload",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/admin": typeof adminAdminRoute;
  "/auth": typeof authAuthRoute;
  "/playgrounds": typeof publicPlaygroundsRoute;
  "/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/~/artist/dashboard": typeof mainChar126ArtistDashboardIndexRoute;
  "/~/artist/my-models": typeof mainChar126ArtistMyModelsIndexRoute;
  "/~/artist/publishing": typeof mainChar126ArtistPublishingIndexRoute;
  "/~/general/cart": typeof mainChar126GeneralCartIndexRoute;
  "/~/general/explore": typeof mainChar126GeneralExploreIndexRoute;
  "/~/general/favorites": typeof mainChar126GeneralFavoritesIndexRoute;
  "/~/general/feed": typeof mainChar126GeneralFeedIndexRoute;
  "/~/general/invoices": typeof mainChar126GeneralInvoicesIndexRoute;
  "/~/general/purchased-models": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/~/general/wishlists": typeof mainChar126GeneralWishlistsIndexRoute;
  "/~/general/payments/receipt": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/admin": typeof adminAdminRoute;
  "/auth": typeof authAuthRoute;
  "/playgrounds": typeof publicPlaygroundsRoute;
  "/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/~/artist/dashboard": typeof mainChar126ArtistDashboardIndexRoute;
  "/~/artist/my-models": typeof mainChar126ArtistMyModelsIndexRoute;
  "/~/artist/publishing": typeof mainChar126ArtistPublishingIndexRoute;
  "/~/general/cart": typeof mainChar126GeneralCartIndexRoute;
  "/~/general/explore": typeof mainChar126GeneralExploreIndexRoute;
  "/~/general/favorites": typeof mainChar126GeneralFavoritesIndexRoute;
  "/~/general/feed": typeof mainChar126GeneralFeedIndexRoute;
  "/~/general/invoices": typeof mainChar126GeneralInvoicesIndexRoute;
  "/~/general/purchased-models": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/~/general/wishlists": typeof mainChar126GeneralWishlistsIndexRoute;
  "/~/general/payments/receipt": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/(admin)/admin": typeof adminAdminRoute;
  "/(auth)/auth": typeof authAuthRoute;
  "/(public)/playgrounds": typeof publicPlaygroundsRoute;
  "/(main)/~/artist": typeof mainChar126ArtistRouteRouteWithChildren;
  "/(main)/~/general": typeof mainChar126GeneralRouteRouteWithChildren;
  "/(main)/~/general/assets/$assetId": typeof mainChar126GeneralAssetsAssetIdRoute;
  "/(main)/~/general/payments/$status": typeof mainChar126GeneralPaymentsStatusRoute;
  "/(main)/~/general/u/$userId": typeof mainChar126GeneralUUserIdRoute;
  "/(main)/~/artist/dashboard/": typeof mainChar126ArtistDashboardIndexRoute;
  "/(main)/~/artist/my-models/": typeof mainChar126ArtistMyModelsIndexRoute;
  "/(main)/~/artist/publishing/": typeof mainChar126ArtistPublishingIndexRoute;
  "/(main)/~/general/cart/": typeof mainChar126GeneralCartIndexRoute;
  "/(main)/~/general/explore/": typeof mainChar126GeneralExploreIndexRoute;
  "/(main)/~/general/favorites/": typeof mainChar126GeneralFavoritesIndexRoute;
  "/(main)/~/general/feed/": typeof mainChar126GeneralFeedIndexRoute;
  "/(main)/~/general/invoices/": typeof mainChar126GeneralInvoicesIndexRoute;
  "/(main)/~/general/purchased-models/": typeof mainChar126GeneralPurchasedModelsIndexRoute;
  "/(main)/~/general/wishlists/": typeof mainChar126GeneralWishlistsIndexRoute;
  "/(main)/~/general/payments/receipt/": typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/auth"
    | "/playgrounds"
    | "/~/artist"
    | "/~/general"
    | "/~/general/assets/$assetId"
    | "/~/general/payments/$status"
    | "/~/general/u/$userId"
    | "/~/artist/dashboard"
    | "/~/artist/my-models"
    | "/~/artist/publishing"
    | "/~/general/cart"
    | "/~/general/explore"
    | "/~/general/favorites"
    | "/~/general/feed"
    | "/~/general/invoices"
    | "/~/general/purchased-models"
    | "/~/general/wishlists"
    | "/~/general/payments/receipt";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/auth"
    | "/playgrounds"
    | "/~/artist"
    | "/~/general"
    | "/~/general/assets/$assetId"
    | "/~/general/payments/$status"
    | "/~/general/u/$userId"
    | "/~/artist/dashboard"
    | "/~/artist/my-models"
    | "/~/artist/publishing"
    | "/~/general/cart"
    | "/~/general/explore"
    | "/~/general/favorites"
    | "/~/general/feed"
    | "/~/general/invoices"
    | "/~/general/purchased-models"
    | "/~/general/wishlists"
    | "/~/general/payments/receipt";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/(admin)/admin"
    | "/(auth)/auth"
    | "/(public)/playgrounds"
    | "/(main)/~/artist"
    | "/(main)/~/general"
    | "/(main)/~/general/assets/$assetId"
    | "/(main)/~/general/payments/$status"
    | "/(main)/~/general/u/$userId"
    | "/(main)/~/artist/dashboard/"
    | "/(main)/~/artist/my-models/"
    | "/(main)/~/artist/publishing/"
    | "/(main)/~/general/cart/"
    | "/(main)/~/general/explore/"
    | "/(main)/~/general/favorites/"
    | "/(main)/~/general/feed/"
    | "/(main)/~/general/invoices/"
    | "/(main)/~/general/purchased-models/"
    | "/(main)/~/general/wishlists/"
    | "/(main)/~/general/payments/receipt/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  adminAdminRoute: typeof adminAdminRoute;
  publicPlaygroundsRoute: typeof publicPlaygroundsRoute;
  mainChar126ArtistRouteRoute: typeof mainChar126ArtistRouteRouteWithChildren;
  mainChar126GeneralRouteRoute: typeof mainChar126GeneralRouteRouteWithChildren;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/imagekit/upload": typeof ApiImagekitUploadServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/auth/$" | "/api/imagekit/upload";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$" | "/api/imagekit/upload";
  id: "__root__" | "/api/auth/$" | "/api/imagekit/upload";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiImagekitUploadServerRoute: typeof ApiImagekitUploadServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/playgrounds": {
      id: "/(public)/playgrounds";
      path: "/playgrounds";
      fullPath: "/playgrounds";
      preLoaderRoute: typeof publicPlaygroundsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/auth": {
      id: "/(auth)/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof authAuthRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(admin)/admin": {
      id: "/(admin)/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof adminAdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/~/general": {
      id: "/(main)/~/general";
      path: "/~/general";
      fullPath: "/~/general";
      preLoaderRoute: typeof mainChar126GeneralRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/~/artist": {
      id: "/(main)/~/artist";
      path: "/~/artist";
      fullPath: "/~/artist";
      preLoaderRoute: typeof mainChar126ArtistRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/~/general/wishlists/": {
      id: "/(main)/~/general/wishlists/";
      path: "/wishlists";
      fullPath: "/~/general/wishlists";
      preLoaderRoute: typeof mainChar126GeneralWishlistsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/purchased-models/": {
      id: "/(main)/~/general/purchased-models/";
      path: "/purchased-models";
      fullPath: "/~/general/purchased-models";
      preLoaderRoute: typeof mainChar126GeneralPurchasedModelsIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/invoices/": {
      id: "/(main)/~/general/invoices/";
      path: "/invoices";
      fullPath: "/~/general/invoices";
      preLoaderRoute: typeof mainChar126GeneralInvoicesIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/feed/": {
      id: "/(main)/~/general/feed/";
      path: "/feed";
      fullPath: "/~/general/feed";
      preLoaderRoute: typeof mainChar126GeneralFeedIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/favorites/": {
      id: "/(main)/~/general/favorites/";
      path: "/favorites";
      fullPath: "/~/general/favorites";
      preLoaderRoute: typeof mainChar126GeneralFavoritesIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/explore/": {
      id: "/(main)/~/general/explore/";
      path: "/explore";
      fullPath: "/~/general/explore";
      preLoaderRoute: typeof mainChar126GeneralExploreIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/cart/": {
      id: "/(main)/~/general/cart/";
      path: "/cart";
      fullPath: "/~/general/cart";
      preLoaderRoute: typeof mainChar126GeneralCartIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/artist/publishing/": {
      id: "/(main)/~/artist/publishing/";
      path: "/publishing";
      fullPath: "/~/artist/publishing";
      preLoaderRoute: typeof mainChar126ArtistPublishingIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/my-models/": {
      id: "/(main)/~/artist/my-models/";
      path: "/my-models";
      fullPath: "/~/artist/my-models";
      preLoaderRoute: typeof mainChar126ArtistMyModelsIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/artist/dashboard/": {
      id: "/(main)/~/artist/dashboard/";
      path: "/dashboard";
      fullPath: "/~/artist/dashboard";
      preLoaderRoute: typeof mainChar126ArtistDashboardIndexRouteImport;
      parentRoute: typeof mainChar126ArtistRouteRoute;
    };
    "/(main)/~/general/u/$userId": {
      id: "/(main)/~/general/u/$userId";
      path: "/u/$userId";
      fullPath: "/~/general/u/$userId";
      preLoaderRoute: typeof mainChar126GeneralUUserIdRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/payments/$status": {
      id: "/(main)/~/general/payments/$status";
      path: "/payments/$status";
      fullPath: "/~/general/payments/$status";
      preLoaderRoute: typeof mainChar126GeneralPaymentsStatusRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/assets/$assetId": {
      id: "/(main)/~/general/assets/$assetId";
      path: "/assets/$assetId";
      fullPath: "/~/general/assets/$assetId";
      preLoaderRoute: typeof mainChar126GeneralAssetsAssetIdRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
    "/(main)/~/general/payments/receipt/": {
      id: "/(main)/~/general/payments/receipt/";
      path: "/payments/receipt";
      fullPath: "/~/general/payments/receipt";
      preLoaderRoute: typeof mainChar126GeneralPaymentsReceiptIndexRouteImport;
      parentRoute: typeof mainChar126GeneralRouteRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/imagekit/upload": {
      id: "/api/imagekit/upload";
      path: "/api/imagekit/upload";
      fullPath: "/api/imagekit/upload";
      preLoaderRoute: typeof ApiImagekitUploadServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authAuthRoute: typeof authAuthRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthRoute: authAuthRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface mainChar126ArtistRouteRouteChildren {
  mainChar126ArtistDashboardIndexRoute: typeof mainChar126ArtistDashboardIndexRoute;
  mainChar126ArtistMyModelsIndexRoute: typeof mainChar126ArtistMyModelsIndexRoute;
  mainChar126ArtistPublishingIndexRoute: typeof mainChar126ArtistPublishingIndexRoute;
}

const mainChar126ArtistRouteRouteChildren: mainChar126ArtistRouteRouteChildren =
  {
    mainChar126ArtistDashboardIndexRoute: mainChar126ArtistDashboardIndexRoute,
    mainChar126ArtistMyModelsIndexRoute: mainChar126ArtistMyModelsIndexRoute,
    mainChar126ArtistPublishingIndexRoute:
      mainChar126ArtistPublishingIndexRoute,
  };

const mainChar126ArtistRouteRouteWithChildren =
  mainChar126ArtistRouteRoute._addFileChildren(
    mainChar126ArtistRouteRouteChildren,
  );

interface mainChar126GeneralRouteRouteChildren {
  mainChar126GeneralAssetsAssetIdRoute: typeof mainChar126GeneralAssetsAssetIdRoute;
  mainChar126GeneralPaymentsStatusRoute: typeof mainChar126GeneralPaymentsStatusRoute;
  mainChar126GeneralUUserIdRoute: typeof mainChar126GeneralUUserIdRoute;
  mainChar126GeneralCartIndexRoute: typeof mainChar126GeneralCartIndexRoute;
  mainChar126GeneralExploreIndexRoute: typeof mainChar126GeneralExploreIndexRoute;
  mainChar126GeneralFavoritesIndexRoute: typeof mainChar126GeneralFavoritesIndexRoute;
  mainChar126GeneralFeedIndexRoute: typeof mainChar126GeneralFeedIndexRoute;
  mainChar126GeneralInvoicesIndexRoute: typeof mainChar126GeneralInvoicesIndexRoute;
  mainChar126GeneralPurchasedModelsIndexRoute: typeof mainChar126GeneralPurchasedModelsIndexRoute;
  mainChar126GeneralWishlistsIndexRoute: typeof mainChar126GeneralWishlistsIndexRoute;
  mainChar126GeneralPaymentsReceiptIndexRoute: typeof mainChar126GeneralPaymentsReceiptIndexRoute;
}

const mainChar126GeneralRouteRouteChildren: mainChar126GeneralRouteRouteChildren =
  {
    mainChar126GeneralAssetsAssetIdRoute: mainChar126GeneralAssetsAssetIdRoute,
    mainChar126GeneralPaymentsStatusRoute:
      mainChar126GeneralPaymentsStatusRoute,
    mainChar126GeneralUUserIdRoute: mainChar126GeneralUUserIdRoute,
    mainChar126GeneralCartIndexRoute: mainChar126GeneralCartIndexRoute,
    mainChar126GeneralExploreIndexRoute: mainChar126GeneralExploreIndexRoute,
    mainChar126GeneralFavoritesIndexRoute:
      mainChar126GeneralFavoritesIndexRoute,
    mainChar126GeneralFeedIndexRoute: mainChar126GeneralFeedIndexRoute,
    mainChar126GeneralInvoicesIndexRoute: mainChar126GeneralInvoicesIndexRoute,
    mainChar126GeneralPurchasedModelsIndexRoute:
      mainChar126GeneralPurchasedModelsIndexRoute,
    mainChar126GeneralWishlistsIndexRoute:
      mainChar126GeneralWishlistsIndexRoute,
    mainChar126GeneralPaymentsReceiptIndexRoute:
      mainChar126GeneralPaymentsReceiptIndexRoute,
  };

const mainChar126GeneralRouteRouteWithChildren =
  mainChar126GeneralRouteRoute._addFileChildren(
    mainChar126GeneralRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  adminAdminRoute: adminAdminRoute,
  publicPlaygroundsRoute: publicPlaygroundsRoute,
  mainChar126ArtistRouteRoute: mainChar126ArtistRouteRouteWithChildren,
  mainChar126GeneralRouteRoute: mainChar126GeneralRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiImagekitUploadServerRoute: ApiImagekitUploadServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
